import json,re
from pathlib import Path
assets=json.loads(Path('scripts/assets.json').read_text()); links=json.loads(Path('qa/commerce-links.json').read_text())
rows=[
('the-gioi','Lược sử thế giới','A Little History of the World','E. H. Gombrich',3,'Lịch sử thế giới',['Thời Đồ đá','Các nền văn minh','Thời đại nguyên tử'],'Một mạch kể giúp bạn nối các biến cố và ý tưởng qua nhiều thời đại.'),
('kinh-te-hoc','Lược sử kinh tế học','A Little History of Economics','Niall Kishtainy',1,'Kinh tế học',['Tiền bạc và thị trường','Lao động','Các tư tưởng kinh tế'],'Bạn sẽ có thêm ngữ cảnh để suy nghĩ về những lựa chọn kinh tế quanh mình.'),
('khao-co-hoc','Lược sử khảo cổ học','A Little History of Archaeology','Brian Fagan',3,'Khảo cổ học',['Những cuộc khai quật','Dấu vết vật chất','Cách đọc quá khứ'],'Theo những dấu vết còn lại, bạn sẽ thấy cách tri thức về quá khứ được hình thành.'),
('tam-ly-hoc','Lược sử tâm lý học','A Little History of Psychology','Nicky Hayes',0,'Tâm lý học',['Freud','Hành vi luận','Tâm lý học nhân văn','Khoa học nhận thức'],'Các trường phái giúp bạn nhìn rõ hơn những cách khác nhau để tìm hiểu con người.'),
('khoa-hoc','Lược sử khoa học','A Little History of Science','William Bynum',1,'Khoa học',['Quan sát và thí nghiệm','Những cuộc tranh luận','Các ý tưởng khoa học'],'Lần theo cách các câu hỏi được đặt ra, bạn sẽ hiểu thêm cách khoa học phát triển.'),
('triet-hoc','Lược sử triết học','A Little History of Philosophy','Nigel Warburton',0,'Triết học',['Socrates','Tự do và linh hồn','Đạo đức','Cách sống'],'Mỗi vấn đề là một dịp thử xem bạn tin điều gì, và vì sao.'),
('hoa-ky','Lược sử Hoa Kỳ','A Little History of the United States','James West Davidson',3,'Lịch sử Hoa Kỳ',['Năm thế kỷ lịch sử','Tự do và bình đẳng','Xung đột và thống nhất'],'Những câu chuyện cụ thể đặt các biến chuyển của Hoa Kỳ vào một mạch lịch sử.'),
('ton-giao','Lược sử tôn giáo','A Little History of Religion','Richard Holloway',0,'Tôn giáo',['Sự hình thành niềm tin','Các truyền thống tôn giáo','Niềm tin và đời sống'],'Một điểm bắt đầu để hiểu các truyền thống và câu hỏi mà tôn giáo đặt ra.'),
('am-nhac','Lược sử âm nhạc','A Little History of Music','Robert Philip',2,'Âm nhạc',['Hát tụng và opera','Nhạc cổ điển','Jazz và hip hop'],'Đọc lịch sử âm nhạc cũng là lắng nghe những thay đổi trong đời sống con người.'),
('ngon-ngu','Câu chuyện ngôn ngữ','A Little Book of Language','David Crystal',2,'Ngôn ngữ',['Tiếng bập bẹ đầu tiên','Ngôn ngữ hằng ngày','Ngôn ngữ mạng'],'Bạn sẽ có dịp quan sát lại cách mình nói, viết và hiểu người khác.'),
('van-chuong','Lược sử văn chương','A Little History of Literature','John Sutherland',2,'Văn chương',['Truyền thống kể chuyện','Người viết và người đọc','Sách điện tử'],'Cuốn sách gợi thêm ngữ cảnh cho những gì bạn đọc và những câu chuyện bạn yêu thích.'),
('toan-hoc','Lược sử toán học','A Little History of Mathematics','Snezana Lawrence',1,'Toán học',['Xương Ishango','Số 0 và đại số','Lý thuyết trò chơi'],'Những ý tưởng toán học được đặt cạnh nhu cầu và trí tưởng tượng của con người.')]
text=Path('codex-pack/04_CONTENT_DECK.md').read_text(); books=[]
for i,(slug,title,en,author,topic,label,highlights,second) in enumerate(rows):
 hook=re.search(r'\*\*'+re.escape(title)+r'\*\*\n> (.+)',text).group(1)
 books.append(dict(slug=slug,titleVi=title,titleEn=en,author=author,translator=None,status='published',primaryTopic=topic,topicTags=[label],hook=hook,description=hook+' '+second,highlights=highlights,**assets[slug],nhanamUrl=links[i]['url'],shopeeUrl=None,sourceNotes=['Approved content deck; local cover visually matched.','Nhà Nam product title and HTTP 200 verified 2026-09-15.','Translator omitted pending legible local verification.']))
books.append(dict(slug='art',titleVi=None,titleEn='A Little History of Art',author='Charlotte Mullins',translator=None,status='forthcoming',primaryTopic=2,topicTags=['Nghệ thuật'],hook='Khoảng 100.000 năm nghệ thuật, qua nhiều nền văn hóa và cách nhìn.',description='Khoảng 100.000 năm nghệ thuật, từ những hình ảnh đầu tiên con người để lại đến các nghệ sĩ của thế giới hiện đại. Charlotte Mullins đặt những cái tên quen thuộc cạnh nhiều nghệ sĩ và truyền thống từng bị đẩy ra ngoài câu chuyện chính, để lịch sử nghệ thuật hiện ra rộng hơn và nhiều tiếng nói hơn.',highlights=['Những hình ảnh đầu tiên','Nghệ sĩ và các truyền thống','Nghệ thuật trong đời sống'],**assets['art'],nhanamUrl=None,shopeeUrl=None,sourceNotes=['https://yalebooks.co.uk/book/9780300278354/a-little-history-of-art/','Local English cover supplied; no approved Vietnamese title.']))
Path('src/data/books.js').write_text('export const books = '+json.dumps(books,ensure_ascii=False,indent=2)+';\n')
